name: Test Build

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/release.yml'
  workflow_dispatch:

env:
  XCODE_PROJECT: video2ppt/Video2PPT.xcodeproj
  SCHEME: Video2PPT

jobs:
  test-build:
    name: Test Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python numpy fpdf2 click matplotlib tqdm
      
      - name: Build App
        run: |
          xcodebuild \
            -project "${{ env.XCODE_PROJECT }}" \
            -scheme "${{ env.SCHEME }}" \
            -configuration Debug \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            | xcpretty
      
      - name: Test Python Module
        run: |
          cd video2ppt
          python -m pytest tests/ || echo "No tests found"
          python -m video2ppt --help
      
      - name: Check Build Output
        run: |
          ls -la video2ppt/build/Build/Products/Debug/ || true
          
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Lint Python
        run: |
          pip install flake8 black
          flake8 video2ppt/ --max-line-length=100 || true
          black --check video2ppt/ || true
      
      - name: Check Swift Format
        run: |
          echo "Swift formatting check skipped (requires macOS)"